spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.13.1.17:5432/aliheyderdb
    username: aliheydar
    password: 6e08pmrw7ew2nr5

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        default_schema: common_ali
  sql:
    init:
      mode: always